### ISSUE TITLE
set up event calendar for 2022

### ISSUE THREAD

**Issue by hansb001** [thin-edge/community#1]

**Comment by hansb001** [comment]
Create a list of interesting conferences and other events for thin-edge.io-team.
For 2022 there are no speaking opportunities (CFP's are closed) and therefore no travel allowed. This agenda should be made for 2023 with clear deadlines to submit speaking proposals.
Agenda should be maintained

**Comment by itsroshan** [comment]
https://github.com/thin-edge/community/blob/main/src/calendar.md
